PhotoShare/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoShare.Models
{
    public class User
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public bool ConfirmPassword { get; set; }
        public List<User> Friends { get; set; } 
        public List<Photo>Photos { get; set; } 
        public Photo Avatar { get; set; }


        public User(string name, string surname, string email)
        {
            Name = name;
            Surname = surname;
            Email = email;
            ConfirmPassword = false;
        }

        public User()
        {
            
        }

        //public User(User user)
        //{
        //    var photos = new List<Photo>();
        //    if (user.Photos != null)
        //        if (user.Photos.Any())
        //            foreach (var photo in photos)
        //            {
        //                var addingPhoto = new Photo(photo.UserId, photo.Image);
        //                if (photo.Comments != null)
        //                    if (photo.Comments.Any())
        //                    {
        //                        foreach (var addingComment in photo.Comments.Select(comment => new Comment(comment.CommentText, comment.CommentOwnerId)))
        //                        {
        //                            photo.Comments.Add(addingComment);
        //                        }
        //                    }
        //                photos.Add(addingPhoto);
        //            }
        //    var friends = new List<User>();
        //    if (user.Friends == null) return;
        //    if (!user.Friends.Any()) return;
        //    foreach (var addingFriend in friends.Select(friend => new User(friend.Name, friend.Surname, friend.Email)))
        //    {
        //        friends.Add(addingFriend);
        //    }
        //}
    }
}

PhotoShare/Controllers/PhotoController.cs
using System;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using Microsoft.Ajax.Utilities;
using PhotoShare.LogicService;
using PhotoShare.Models;
using Photo = PhotoShare.Domain.Photo;

namespace PhotoShare.Controllers
{
    public class PhotoController : Controller
    {
        readonly UserBl _userBl = new UserBl();
        readonly CommentBl _commentBl = new CommentBl();
        readonly PhotoBl _photoBl = new PhotoBl();

        //
        // GET: /Photo/
        [Authorize]
        public ActionResult AddPhoto()
        {
            var model = new PhotoModel { UrlPhotoPath = "photoUrl"};
            return View(model);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddPhoto(HttpPostedFileBase file, string photoUrl)
        {
            if (!ModelState.IsValid || (file == null && photoUrl.IsNullOrWhiteSpace())) return RedirectToAction("AddPhoto");
            var imageData = new byte[] {};

            if (file != null)
            {
                using (var binaryReader = new BinaryReader(file.InputStream))
                {
                    imageData = binaryReader.ReadBytes(file.ContentLength);
                }
            }
            else
            {
                Uri uriResult;
                var result = Uri.TryCreate(photoUrl, UriKind.Absolute, out uriResult) &&
                              uriResult.Scheme == Uri.UriSchemeHttp;
                if (result)
                {
                   imageData = DownloadImages(photoUrl);
                }
            }
            if (imageData == null) return RedirectToAction("AddPhotoStepTwo");
            if (!imageData.Any()) return RedirectToAction("AddPhotoStepTwo");
            var user = _userBl.GetCurrentUser();
            var photo = new Models.Photo(user.Id, imageData) {Description = "  "};

            TempData["uploadPhoto"] = photo;
            return RedirectToAction("AddPhotoStepTwo");
        }

        public byte[] DownloadImages(string urlImage)
        {
            var remoteImgPath = urlImage;

            try
            {
                var remoteImgPathUri = new Uri(remoteImgPath);
                var remoteImgPathWithoutQuery = remoteImgPathUri.GetLeftPart(UriPartial.Path);
                var fileExtension = Path.GetExtension(remoteImgPathWithoutQuery); // .jpg, .png
                if (fileExtension != ".jpg" && fileExtension != ".png" && fileExtension != ".gif" &&
                    fileExtension != ".bmp") return null;
                var webClient = new WebClient();
                var dataImage = webClient.DownloadData(urlImage);
                return dataImage;
            }
            catch (Exception )
            {
                return null;
            }
        }

        [Authorize]
        public ActionResult AddPhotoStepTwo()
        {
            var photo =(Models.Photo) TempData["uploadPhoto"];
            photo.Description = " ";
            return View(photo);
        }

        [Authorize]
        [HttpPost]
        public ActionResult AddPhotoStepTwo(Photo photo)
        {
            photo.UserId = _userBl.GetCurrentUser().Id;
            photo.DateTime = DateTime.Now;
            _photoBl.CreatePhoto(photo);
            return RedirectToAction("AddPhoto");

        }


        [Authorize]
        public ActionResult PhotoShare()
        {
            var user = _userBl.GetCurrentUser();
            var photos = user.Photos;
            if (!user.Friends.Any()) return View(photos);
            foreach (var friend in user.Friends.Where(friend => friend.Photos.Any()))
            {
                photos.AddRange(friend.Photos);
            }
            photos.Sort();
            return View(photos);
        }


        [Authorize]
        public ActionResult EditDescription(Photo photo)
        {
            if (!ModelState.IsValid) return RedirectToAction("UserProfile", "User", new { userName = _userBl.GetCurrentUser().Name });
            try
            {
                var _photo = _photoBl.GetPhotoById(photo.Id);
                // photo.Description = description;
                _photoBl.UpdatePhoto(photo);

                return RedirectToAction("UserProfile", "User", new { userName = _userBl.GetCurrentUser().Name });
            }
            catch (Exception e)
            {
                ModelState.AddModelError("", e.Message);
            }

            // If we got this far, something failed, redisplay form
            return View(ModelState);
        }

        [Authorize]
        public ActionResult DeleteImage(Guid id)
        {
            _photoBl.DeletePhoto(id);
            return RedirectToAction("UserProfile", "User", new { userName = _userBl.GetCurrentUser().Name });
        }





    }
}

PhotoShare/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PhotoShare.Domain;
using PhotoShare.LogicService;

namespace PhotoShare.Controllers
{
    public class UserController : Controller
    {
        readonly UserBl _userBl = new UserBl();
        readonly CommentBl _commentBl = new CommentBl();
        readonly PhotoBl _photoBl = new PhotoBl();

        [Authorize]
        public ActionResult Search(string searchString)
        {
            if (String.IsNullOrEmpty(searchString)) return View();
            var searchResult =_userBl.SearchUser(searchString);
            return View(searchResult);
        }

        [Authorize]
        public ActionResult UserProfile(string userName)
        {
            var user = userName.IsNullOrWhiteSpace() ? _userBl.GetCurrentUser() : _userBl.SearchUser(userName).First();
            return View(user);
        }
        
        [Authorize]
        [HttpPost]
        public ActionResult UserProfile(User user, Photo currentPhoto)
        {
            return RedirectToAction("UserProfile","User", new{ userName = _userBl.GetUserById(user.Id).Name});
        }

        //[Authorize]
        //public ActionResult EditDescription(Guid id)
        //{
        //    var photo = _photoBl.GetPhotoById(id);
        //    return View(photo);
        //}

       
        [Authorize]
        public ActionResult AddFriend(Guid id)
        {
            var currentUser = _userBl.GetCurrentUser();
            var friend = _userBl.GetUserById(id);
            currentUser.Friends.Add(friend);
            _userBl.UpdateUser(currentUser);
            var user = _userBl.GetCurrentUser();
            return RedirectToAction("UserProfile", "User", new { userName = friend.Name });
        }

        [Authorize]
        public ActionResult DeleteFriend(Guid id)
        {
            var currentUser = _userBl.GetCurrentUser();
            var friend = _userBl.GetUserById(id);
            currentUser.Friends.Remove(friend);
            _userBl.UpdateUser(currentUser);

            return RedirectToAction("Friends", "User");
        }

        [Authorize]
        public ActionResult Friends()
        {
            var user = _userBl.GetCurrentUser();
            return View(user);
        }



    }
}

PhotoShare/Views/User/EditDescription.cshtml
@model PhotoShare.Domain.Photo
@{
    ViewBag.Title = "EditDescription";
}




@Html.Raw("<img class = 'preview' style='max-height: 50vh;max-width: 70vw;' src=\"data:image/jpeg;base64,"
                  + Convert.ToBase64String(Model.Image) + "\" />")


    @using (Html.BeginForm("EditDescription", "Photo", FormMethod.Post))
    {

        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => Model.Id)
        <div>
            @Html.EditorFor(p=>p.Description)
            @Html.ValidationMessageFor(x => x.Description)
        </div>
        <div>
            <input type="submit" value="Изменить описание">
        </div>
     }

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotoShare/Views/User/Friends.cshtml
@{
    ViewBag.Title = "Friends";
}

@model PhotoShare.Domain.User
<h2>Friends</h2>

@if (!Model.Friends.Any())
{
    const string noFriends = "У Вас сейчас нет друзей :(";
    @Html.Label(noFriends);
}
else
{
    <table>
    @foreach (var friend in Model.Friends)
    {
        <tr>
            <td>
                @Html.ActionLink(friend.Name, "UserProfile", "User", new{userName = friend.Name}, null)
            </td>
            
            <td>
                @Html.ActionLink("Delete friend", "DeleteFriend", "User", new {id = friend.Id}, null)
            </td>
        </tr>
    }
        </table>
}

PhotoShare/Views/User/Search.cshtml
@{
    ViewBag.Title = "Search";
}

@using Microsoft.Ajax.Utilities
@model List<PhotoShare.Domain.User>

@if (Model != null)
{
    <ul>
        @foreach (var person in Model)
        {
            <li>
                @Html.ActionLink(person.Name + " " + person.Surname, "UserProfile", "User", new { userName = person.Name}, null)
            </li>
        }
    </ul>
}

PhotoShare/Views/User/UserProfile.cshtml
@model PhotoShare.Domain.User

@{
    ViewBag.Title = Model.Name;
}


@if (Model != null)
{
    string imgSrc;
    if (Model.Avatar != null)
    {
        var base64 = Convert.ToBase64String(Model.Avatar);
        imgSrc = String.Format("data:image/gif;base64,{0}", base64);
    }
     else
    {
        imgSrc = "/Images/defaultAvatar.jpg";
    }
    <p >
        <a href="@Url.Action("Index", "Home")">
            <img src="@imgSrc" id="avatar"/>
            <h2> @Html.Label(Model.Name + " " + Model.Surname)</h2>
        </a>
    </p>
    @((Model.Name == HttpContext.Current.User.Identity.Name || User.IsInRole("admin")) ? Html.Partial("_CurrentUserProfilePartial", Model) : Html.Partial("_UserProfilePartial", Model))
}

PhotoShare/Views/User/_CurrentUserProfilePartial.cshtml
@using PhotoShare.Domain
@model PhotoShare.Domain.User

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="~/Scripts/my_scripts.js"></script>


@using (Html.BeginForm("UserProfile", "User", FormMethod.Post))
       
{
    <div>
        <p>
            <input type="hidden" name="Id" value=@Model.Id />
                   
            <a href="@Url.Action("AddPhoto", "Photo")">
                <button> @Html.Label("Добавить новое изображение")</button>
            </a>
        </p>
    </div>
    
     if (Model != null)
      {

         if(Model != null)
        {
        if(Model.Photos != null)
        {
            if (Model.Photos.Any())
            {
                @Html.Label("Вы можете удалить фотографии или изменить описание")
                foreach (var photo in Model.Photos)
                {
                    @Html.Partial("_EditDescriptionPartial", photo)
                }
            }
            else
            {
                 @Html.Label("У Вас сейчас нет фотографий")
            }
          }
        }
    }
}


    

        

PhotoShare/Views/User/_EditDescriptionPartial.cshtml
@{
    ViewBag.Title = "_EditDescriptionPartial";
}

@model PhotoShare.Domain.Photo

<form id="photoForm">
                        
    @Html.Raw("<img class = 'preview' style='max-height: 20vh;max-width: 70vw;' " +
              "src=\"data:image/jpeg;base64,"
              + Convert.ToBase64String(Model.Image) + "\" />")
    <p>
        @Html.Label("Current desription: ")
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div>
            @Html.HiddenFor(x=>x.Id)
            @Html.EditorFor(x => x.Description, new {PlaceHolderAttribute = "Description"})
            @Html.ValidationMessageFor(x => Model.Description)
        </div>
        
        @Html.ActionLink("Edit description", "EditDescription", "Photo", new{description = Model.Description})
        @Html.ActionLink("Delete", "DeleteImage", "Photo", new {id = Model.Id}, null)
    </p>
</form>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PhotoShare/Views/User/_UserProfilePartial.cshtml
@using PhotoShare.LogicService
@model PhotoShare.Domain.User

<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="~/Scripts/my_scripts.js"></script>


@using (Html.BeginForm("UserProfile", "User", FormMethod.Post, new {enctype = "multipart/form-data"}))
{
    var userBl = new UserBl();
    var user = userBl.GetCurrentUser();
    if (user.Friends != null)
    {
        <input type="hidden" name="Id" value=Model.Id />
        @(!userBl.IsFriend(Model.Id) ? Html.ActionLink("Add friend", "AddFriend", "User", new {id = Model.Id}, null) :
        Html.ActionLink("Delete friend", "DeleteFriend", "User", new {id = Model.Id}, null))
    }
   
}



@if (Model != null)
    {

        if (Model.Photos != null)
        {
            if (Model.Photos.Any())
            {
                
                for (var index = 0; index < Model.Photos.Count; index++)
                {
                    var base64 = Convert.ToBase64String(Model.Photos[index].Image);
                    var imgSrc = String.Format("data:image/gif;base64,{0}", base64);

                    var photo = Model.Photos[index];
                    <form>
                                  
                        <div>
                            <p><a class="show_popup" rel="@String.Format("photo_win{0}", index)" href="#"><img src="@imgSrc"  alt="Photo" id="profilePhoto"/></a></p>
                              
                        </div>
                        <div class="@String.Format("popup photo_win{0}", index)">
                            <a class="close" href="#">Close</a>
                            <div class="img_wrap">
                                <p align="center">
                                <img src="@imgSrc" id="popupImage"/>
                                <p>
                                    @Html.Label(photo.Description)

                                </p>					
                            </div>
                        </div>
                          
                    </form>
                }

            }
        }
    }

    