PhotoShare/Models/Administrator.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoShare.Models
{
    public class Administrator : User
    {
        public Administrator(string name, string surname, string email, string password)
            : base(name, surname, email)
        {
            ConfirmPassword = true;
        }
    }
}

PhotoShare/Models/Comment.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoShare.Models
{
    public class Comment
    {
        public Comment(string text, int ownerCommentId)
        {
            CommentText = text;
            CommentOwnerId = ownerCommentId;
            Date = DateTime.Now;
        }
        public string CommentText { get; set; }
        public int CommentOwnerId { get; private set; }
        public DateTime Date { get; private set; }
    }
}

PhotoShare/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace PhotoShare.Models
{
    public class User
    {
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public bool ConfirmPassword { get; set; }
        public List<User> Friends { get; set; } 
        public List<Photo>Photos { get; set; } 
        public Photo Avatar { get; set; }


        public User(string name, string surname, string email)
        {
            Name = name;
            Surname = surname;
            Email = email;
            ConfirmPassword = false;
        }

        public User()
        {
            
        }

        //public User(User user)
        //{
        //    var photos = new List<Photo>();
        //    if (user.Photos != null)
        //        if (user.Photos.Any())
        //            foreach (var photo in photos)
        //            {
        //                var addingPhoto = new Photo(photo.UserId, photo.Image);
        //                if (photo.Comments != null)
        //                    if (photo.Comments.Any())
        //                    {
        //                        foreach (var addingComment in photo.Comments.Select(comment => new Comment(comment.CommentText, comment.CommentOwnerId)))
        //                        {
        //                            photo.Comments.Add(addingComment);
        //                        }
        //                    }
        //                photos.Add(addingPhoto);
        //            }
        //    var friends = new List<User>();
        //    if (user.Friends == null) return;
        //    if (!user.Friends.Any()) return;
        //    foreach (var addingFriend in friends.Select(friend => new User(friend.Name, friend.Surname, friend.Email)))
        //    {
        //        friends.Add(addingFriend);
        //    }
        //}
    }
}

PhotoShare/Controllers/AdministratorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using PhotoShare.Domain;
using PhotoShare.LogicService;
using WebMatrix.WebData;

namespace PhotoShare.Controllers
{
    public class AdministratorController : Controller
    {
        readonly UserBl _userBl = new UserBl();
        readonly CommentBl _commentBl = new CommentBl();
        readonly PhotoBl _photoBl = new PhotoBl();
        
        // GET: /Administrator/

        public ActionResult Index()
        {
            //if (!User.IsInRole("admin"))
            //    return RedirectToAction("NoAccess");

            return View();
        }

        public ActionResult Users()
        {
            if (!User.IsInRole("admin"))
                return RedirectToAction("NoAccess");
            var users = _userBl.GetAllUsers();
            return View(users);
        }

        public ActionResult DeleteUser(Guid id)
        {
            var user = _userBl.GetUserById(id);
            Membership.Provider.DeleteUser(user.Name, true);
            _userBl.DeleteUser(id);
            return RedirectToAction("Users");
        }

        public ActionResult Comments()
        {
            if (!User.IsInRole("admin"))
                return RedirectToAction("NoAccess");

            var comments = _commentBl.GetAllComments();
            comments.Sort();
            return View(comments);
        }

        public ActionResult DeleteComment(Guid id)
        {
            _commentBl.DeleteComment(id);
            return RedirectToAction("Comments");
        }

        public ActionResult EditComment(Guid id)
        {
            var comment = _commentBl.GetCommentById(id);
            return View(comment);
        }

        [HttpPost]
        public ActionResult EditComment(Comment comment)
        {
            var editComment = _commentBl.GetCommentById(comment.Id);
            editComment.CommentText = comment.CommentText;
            _commentBl.UpdateComment(editComment);
            return RedirectToAction("Comments");
        }

        public ActionResult Posts()
        {
            if (!User.IsInRole("admin"))
                return RedirectToAction("NoAccess");

            return View();
        }

        public ActionResult StaticPages()
        {
            if (!User.IsInRole("admin"))
                return RedirectToAction("NoAccess");

            return View();
        }

        public ActionResult NoAccess()
        {
            return View();
        }

    }
}

PhotoShare/Controllers/UserController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PhotoShare.Domain;
using PhotoShare.LogicService;

namespace PhotoShare.Controllers
{
    public class UserController : Controller
    {
        readonly UserBl _userBl = new UserBl();
        readonly CommentBl _commentBl = new CommentBl();
        readonly PhotoBl _photoBl = new PhotoBl();

        [Authorize]
        public ActionResult Search(string searchString)
        {
            if (String.IsNullOrEmpty(searchString)) return View();
            var searchResult =_userBl.SearchUser(searchString);
            return View(searchResult);
        }

        [Authorize]
        public ActionResult UserProfile(string userName)
        {
            var user = userName.IsNullOrWhiteSpace() ? _userBl.GetCurrentUser() : _userBl.SearchUser(userName).First();
            return View(user);
        }
        
        [Authorize]
        [HttpPost]
        public ActionResult UserProfile(User user, Photo currentPhoto)
        {
            return RedirectToAction("UserProfile","User", new{ userName = _userBl.GetUserById(user.Id).Name});
        }

        //[Authorize]
        //public ActionResult EditDescription(Guid id)
        //{
        //    var photo = _photoBl.GetPhotoById(id);
        //    return View(photo);
        //}

       
        [Authorize]
        public ActionResult AddFriend(Guid id)
        {
            var currentUser = _userBl.GetCurrentUser();
            var friend = _userBl.GetUserById(id);
            currentUser.Friends.Add(friend);
            _userBl.UpdateUser(currentUser);
            var user = _userBl.GetCurrentUser();
            return RedirectToAction("UserProfile", "User", new { userName = friend.Name });
        }

        [Authorize]
        public ActionResult DeleteFriend(Guid id)
        {
            var currentUser = _userBl.GetCurrentUser();
            var friend = _userBl.GetUserById(id);
            currentUser.Friends.Remove(friend);
            _userBl.UpdateUser(currentUser);

            return RedirectToAction("Friends", "User");
        }

        [Authorize]
        public ActionResult Friends()
        {
            var user = _userBl.GetCurrentUser();
            return View(user);
        }



    }
}

PhotoShare/Views/Administrator/Comments.cshtml
@{
    ViewBag.Title = "Comments";
}

@model List<PhotoShare.Domain.Comment>
<h2>Comments</h2>

@if (Model != null)
{
    if (Model.Any())
    {
        <table>
            @foreach (var comment in Model)
            {
                <tr>
                    <td>
                        @Html.Label(comment.CommentText)
                    </td>
                    <td>
                        @Html.ActionLink(comment.CommentOwner.Name + " " + comment.CommentOwner.Surname, "UserProfile", "User", new { userName = comment.CommentOwner.Name}, null)
                    </td>
                    <td>
                        @Html.Label(comment.Date.ToString())
                    </td>
                    <td>
                        @Html.ActionLink("Delete Comment", "DeleteComment", "Administrator", new{id = comment.Id}, null)
                    </td>
                    <td>
                        @Html.ActionLink("Edit Comment", "EditComment", "Administrator", new{id = comment.Id}, null)
                    </td>

                </tr>
            }
        </table>
    }
}

PhotoShare/Views/Administrator/EditComment.cshtml
@{
    ViewBag.Title = "EditComment";
}

@model PhotoShare.Domain.Comment
<h2>EditComment</h2>

 @using (Html.BeginForm("Edit Comment", "EditComment", FormMethod.Post))
    {
        
        @Html.AntiForgeryToken()
        @Html.ValidationSummary(true)
        <div>
            @Html.HiddenFor(m=>m.Id)
            @Html.EditorFor(x => x.CommentText,new { PlaceHolderAttribute = "Comment"})
        </div>
        <div>
            <input type="submit" value="Edit comment">
        </div>
     }

PhotoShare/Views/Administrator/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Администрирование</h2>

<ul>
    <li>@Html.ActionLink("Users", "Users","Administrator")</li>
    <li>@Html.ActionLink("Comments", "Comments", "Administrator")</li>
    <li>@Html.ActionLink("Posts", "Posts", "Administrator")</li>
    <li>@Html.ActionLink("Static Pages", "StaticPages", "Administrator")</li>
    <li>@Html.ActionLink("Roles", "RoleCreate", "Account")</li>
</ul>


PhotoShare/Views/Administrator/NoAccess.cshtml
@{
    ViewBag.Title = "NoAccess";
}

<h2>У Вас нет прав для просмотра этой страницы</h2>

PhotoShare/Views/Administrator/Users.cshtml
@{
    ViewBag.Title = "Users";
}
@model List<PhotoShare.Domain.User>
<h2>Users</h2>

@if (Model != null)
{
    if (Model.Any())
    {
        <table>
            @foreach (var user in Model)
            {
                <tr>
                    <td>
                        @Html.ActionLink(user.Name + " " + user.Surname, "UserProfile", "User", new { userName = user.Name}, null)
                    </td>
                    <td>
                        @Html.ActionLink("Delete User", "DeleteUser", "Administrator", new{id = user.Id}, null)
                    </td>
                </tr>
            }
        </table>
    }
}